### ISSUE TITLE
Use input type email

### ISSUE THREAD

**Issue by ahmadalfy** [nada-fadali/ui-shoppingcart#2]
https://github.com/nada-fadali/ui-shoppingcart/blob/master/index.html#L86

This will force the browsers to validate the user input and make sure that it is an email without using any 3rd party libraries.

**Comment by nada-fadali** [comment]
[fixed](https://github.com/nada-fadali/ui-shoppingcart/commit/53b6deeb831a9563d4c4713fa7018b5bd4becb00)
