### ISSUE TITLE
Generate complete font-face kit

### ISSUE THREAD

**Issue by ahmadalfy** [nada-fadali/ui-shoppingcart#3]
You are only including .ttf font

https://github.com/nada-fadali/ui-shoppingcart/blob/master/styles/style.css#L1-L4

We didn't discuss that yet so keep this issue open till we discuss the fonts

**Comment by nada-fadali** [comment]
[did I do this right?](https://github.com/nada-fadali/ui-shoppingcart/commit/32bb14582294fd68bc5996d3e578bc0cbcef4402)

**Comment by ahmadalfy** [comment]
Yes, perfect!
