### ISSUE TITLE
zero values on position related properties for footer

### ISSUE THREAD

**Issue by ahmadalfy** [nada-fadali/ui-shoppingcart#4]
https://github.com/nada-fadali/ui-shoppingcart/blob/master/styles/style.css#L312-L313

These values has zero effect :) The footer isn't moving anywhere. Why are you using them??

**Comment by nada-fadali** [comment]
I don't have any reason tbh, I wasn't thinking when I did that :sweat_smile: 
[fixed](https://github.com/nada-fadali/ui-shoppingcart/commit/4b760d58f90023df682c2e64c056d99885cc98ab)
